language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py35-django1.8-drf3.2

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
